language: clojure
lein: lein2
script: lein2 midje
notifications:
  irc: "irc.freenode.org#clj-postgresql"
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
addons:
  postgresql: 9.3
before_script:
  - psql -c 'CREATE DATABASE clj_pg_test;' postgres
after_failure:
  - psql -c '\d' -U postgres
  - sudo cat /var/log/postgresql/postgresql-9.3-main.log
env: PGDATABASE='clj_pg_test' PGUSER='postgres'
